# This is a boilerplate parameters config generated for pipeline 'data_science'
# using Kedro 0.17.4.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/0.17.4/04_kedro_project_setup/02_configuration.html#parameters
num_train_iter: 10000
learning_rate: 0.01

target_col: species